### PR TITLE
Support more escape characters in string literals

### PR DESCRIPTION
**Pull request by itchyny**
This PR allows to use more escape characters (`\t`, `\f`, `\b`, `\/`) to make it more compatible with jq (note that these escape characters are supported in [JSON](https://json.org)). Of course this is not perfect (`\uXXXX` is missing), I'm wondering how to implement the rest (need to add double quotes and use `fromjson`? or `implode` helps us?).

### CODE REVIEW

**Comment by wader** [comment]
👍  Yeah hmm i can't come up with any other solution for `\uXXXX`. So either we would reconstruct a JSON string (don't do any unescape at all) and use `fromjson` on it? or per unicode escape convert hex to number and implode?

Maybe more fun and educating to do the implode variant?

**Comment by wader** [comment]
Added unicode codepoint escape support https://github.com/wader/jqjq/commit/8639a02c401b2e5b735e921edc343b7ccca8b668

Let me if you know some neater way to do it. With this done i've thought about maybe implement  `fromjson`/`tojson` using the jqjq parser? will be much slower but more interesting :)

**Comment by itchyny** [comment]
The implementation looks nice. I think `_fromradix` can be simplified.
```jq
def _fromradix($base; tonum):
  reduce split("")[] as $c (0;
    . * $base + ($c | tonum)
  );
```

**Comment by wader** [comment]
Thanks, did a variant of that https://github.com/wader/jqjq/commit/0c4593b3beeae07381bb6eace9a454970be225b8

**Pull request merged**
